version: "3.8"

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app-network

  postgresql:
    image: postgres:latest
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - postgresql
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./server:/src
    environment:
      MONGO_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOSTNAME: mongodb
      MONGO_PORT: 27017
      MONGO_DB: mongodb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOSTNAME: postgresql
      POSTGRES_PORT: 5432
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
      - client
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/dist:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network

  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./fail2ban/config:/config
      - ./nginx/log:/remotelogs/nginx:ro
    environment:
      - PGID=1000
      - PUID=1000
    restart: unless-stopped
    networks:
      - app-network

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email hamzamahmood93150@gmail.com --agree-tos --no-eff-email
             -d sellerto.store

  certbot-cron:
    container_name: certbot-cron
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "echo '0 0,12 * * * root certbot renew --webroot --webroot-path=/var/www/certbot --quiet --deploy-hook \"docker-compose restart nginx\"' > /etc/crontabs/root && crond -f -d 8"
    restart: unless-stopped

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mongodb-data:
  postgresql-data:
  fail2ban-data:
  certbot-conf:
  certbot-www:

networks:
  app-network:
